=== isaaccp2097/LM_1617_inma_morilla/U2/P1/ex3.dtd
<!ELEMENT catenemontuose (catenamontuosa*)>
<!ELEMENT catenamontuosa (nombre,monte+)>
<!ELEMENT monte (nome, regione?, altezza?)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT regione (#PCDATA)>
<!ELEMENT altezza (#PCDATA)>
<!ATTLIST altezza unitamisura CDATA #REQUIRED>

=== isaaccp2097/LM_1617_inma_morilla/U1/P2/ex3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catenemontuose SYSTEM "ex3.dtd">
<catenemontuose>
  <catenamontuosa>
    <monte>
      <nome>Picos de Ba√±uela</nome>
      <regione>Andalucia</regione>
      <altezza unitamisura="metros">1324</altezza>
    </monte>
    <monte>
	    <nome>Corral de borros</nome>
      <regione>Andalucia</regione>
      <altezza unitamisura="metros">1312</altezza>
    </monte>
  </catenamontuosa>
</catenemontuose>
