=== isaaccp2097/LM_1617_inma_morilla/U1/P2/ex5.dtd
<!ELEMENT partido (equipos-enfrentados,resultado,equipo+)>
<!ELEMENT equipos-enfrentados (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT equipo (nombre-equipo,goleador?,sancionados?,goles?,lesionados?)>
<!ELEMENT nombre-equipo (#PCDATA)>
<!ELEMENT goleador (#PCDATA)>
<!ELEMENT sancionados (amarilla*,roja*)>
<!ELEMENT amarilla (jugador+)>
<!ELEMENT jugador (#PCDATA)>
<!ATTLIST jugador num CDATA #REQUIRED>
<!ELEMENT roja (#PCDATA)>
<!ELEMENT goles (marcado+)>
<!ELEMENT marcado (minuto,motivo)>
<!ELEMENT minuto (#PCDATA)>
<!ELEMENT motivo (#PCDATA)>
<!ELEMENT lesionados (nombre*)>
<!ELEMENT nombre (#PCDATA)>

=== isaaccp2097/LM_1617_inma_morilla/U1/P2/ex5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partido SYSTEM "ex5.dtd">

<partido>
	<equipos-enfrentados>Sevilla-Alavés</equipos-enfrentados>
	<resultado>2-1</resultado>
	<equipo>
		<nombre-equipo>Sevilla F.C</nombre-equipo>
		<goleador>W.Ben Yedder</goleador>
		<sancionados>
			<amarilla>
				<jugador num="24">G. Mercado</jugador>
				<jugador num="3">Mariano</jugador>
			</amarilla>
		</sancionados>

		<goles>
			<marcado>
				<minuto>74</minuto>
				<motivo>Jugada</motivo>
			</marcado>
			<marcado>
				<minuto>90</minuto>
				<motivo>Jugada</motivo>
			</marcado>
		</goles>
		<lesionados>
			<nombre>S.Nasri</nombre>
			<nombre>L.Vietto</nombre>
		</lesionados>
	</equipo>
	<equipo>
		<nombre-equipo>D. Alavés</nombre-equipo>
		<goleador>Laguardia</goleador>
		<sancionados>
			<amarilla>
				<jugador num="4">Alexis</jugador>
				<jugador num="15">Theo Hernández</jugador>
				<jugador num="3">Raúl García</jugador>
				<jugador num="6">Marcos Llorente</jugador>
				<jugador num="17">Édgar Méndez</jugador>
				<jugador num="19">Manu García</jugador>
			</amarilla>
		</sancionados>
		<goles>
			<marcado>
				<minuto>84</minuto>
				<motivo>Jugada</motivo>
			</marcado>
		</goles>
		<lesionados>
			<nombre>Kiko Femenía</nombre>
			<nombre>D. Torres</nombre>
			<nombre>Camarasa</nombre>
			<nombre>A. Pantić </nombre>
		</lesionados>
	</equipo>
</partido>
